

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';

export const GET_ENTRIES = 'GET_ENTRIES';
export const IS_LOADING = 'IS_LOADING';
export const GET_ENTRIES_ERROR = 'GET_ENTRIES_ERROR'
